"""Selenium-based YouTube session manager (anti-bot infrastructure).

YouTube blocks datacenter-style requests with "Sign in to confirm you're not
a bot". This module runs a real Chrome browser with a persistent app-owned
profile, visits YouTube to establish a genuine session, and exports the
cookies to Netscape-format cookies.txt for yt-dlp.

Shared by ALL workers (local orchestrator + future Celery workers): they all
call pipeline.download_video(), which calls ensure_cookies() first.

CLI:
    python browser_session.py --login     # visible browser, log in once (stored in profile)
    python browser_session.py --refresh   # headless refresh of cookies.txt
"""
import argparse
import logging
import time
from pathlib import Path
from typing import Optional

logger = logging.getLogger("browser_session")

COOKIES_FILE = Path("cookies.txt")
PROFILE_DIR = Path("browser_profile")
DEFAULT_REFRESH_HOURS = 12

# Cookies that indicate a real, established YouTube session
_SESSION_COOKIE_HINTS = {"VISITOR_INFO1_LIVE", "YSC", "__Secure-YEC", "SID", "SAPISID"}


def _make_driver(headless: bool):
    from selenium import webdriver
    from selenium.webdriver.chrome.options import Options

    opts = Options()
    opts.add_argument(f"--user-data-dir={PROFILE_DIR.resolve()}")
    if headless:
        opts.add_argument("--headless=new")
    opts.add_argument("--disable-blink-features=AutomationControlled")
    opts.add_argument("--no-first-run")
    opts.add_argument("--no-default-browser-check")
    opts.add_argument("--window-size=1280,900")
    opts.add_experimental_option("excludeSwitches", ["enable-automation"])
    opts.add_experimental_option("useAutomationExtension", False)

    driver = webdriver.Chrome(options=opts)  # Selenium Manager auto-fetches chromedriver
    driver.set_page_load_timeout(60)
    return driver


def _write_netscape(cookies) -> Path:
    """Write cookies in Netscape format (what yt-dlp's cookiefile expects)."""
    lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by browser_session.py - do not edit manually",
        "",
    ]
    for c in cookies:
        domain = c.get("domain", "")
        if not domain:
            continue
        flag = "TRUE" if domain.startswith(".") else "FALSE"
        path = c.get("path", "/")
        secure = "TRUE" if c.get("secure") else "FALSE"
        expiry = c.get("expiry") or int(time.time()) + 30 * 24 * 3600
        lines.append(f"{domain}\t{flag}\t{path}\t{secure}\t{int(expiry)}\t{c['name']}\t{c['value']}")
    COOKIES_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return COOKIES_FILE


def _session_quality(cookies) -> int:
    """How many session-indicating cookies we got (0 = poor session)."""
    names = {c.get("name") for c in cookies}
    return len(names & _SESSION_COOKIE_HINTS)


def harvest(headless: bool = True, login_timeout: int = 0) -> Optional[Path]:
    """Open YouTube in Selenium Chrome and export cookies.txt.

    login_timeout > 0: keep a visible window open for that many seconds so the
    user can log into YouTube once. The login persists in browser_profile/.
    """
    driver = _make_driver(headless)
    try:
        driver.get("https://www.youtube.com")
        time.sleep(3)

        if login_timeout > 0:
            logger.info("Visible browser opened - log into YouTube within %ds...", login_timeout)
            deadline = time.time() + login_timeout
            while time.time() < deadline:
                time.sleep(5)
                if _session_quality(driver.get_cookies()) >= 3:
                    logger.info("Login detected.")
                    break

        cookies = driver.get_cookies()
        quality = _session_quality(cookies)
        if not cookies:
            logger.warning("No cookies captured from YouTube.")
            return None
        logger.info("Captured %d cookies (session quality: %d/5).", len(cookies), quality)
        return _write_netscape(cookies)
    finally:
        driver.quit()


def ensure_cookies(max_age_hours: float = DEFAULT_REFRESH_HOURS) -> Optional[Path]:
    """Return a fresh cookies.txt, harvesting headlessly if missing/stale.

    Safe to call from every worker before every download - it only launches
    the browser when the file is older than max_age_hours.
    """
    if COOKIES_FILE.exists():
        age_h = (time.time() - COOKIES_FILE.stat().st_mtime) / 3600
        if age_h < max_age_hours:
            return COOKIES_FILE

    logger.info("cookies.txt missing or stale (%.1fh old) - harvesting via Selenium...", 
                (time.time() - COOKIES_FILE.stat().st_mtime) / 3600 if COOKIES_FILE.exists() else -1)
    try:
        return harvest(headless=True)
    except Exception as e:
        logger.warning("Headless harvest failed: %s", e)
        if COOKIES_FILE.exists():
            logger.info("Falling back to existing (stale) cookies.txt")
            return COOKIES_FILE
        return None


def main() -> int:
    logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(name)s: %(message)s")
    p = argparse.ArgumentParser(description="YouTube cookie harvester for yt-dlp")
    p.add_argument("--login", action="store_true", help="open visible browser to log into YouTube once")
    p.add_argument("--refresh", action="store_true", help="headless refresh of cookies.txt")
    p.add_argument("--timeout", type=int, default=180, help="login wait seconds (with --login)")
    args = p.parse_args()

    if args.login:
        path = harvest(headless=False, login_timeout=args.timeout)
    elif args.refresh:
        path = harvest(headless=True)
    else:
        p.print_help()
        return 2

    if path:
        print(f"OK: cookies written to {path}")
        return 0
    print("FAILED: no cookies captured")
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
